functionality to add webhook settings through post back url
PacktDev/rustici-nodejs pull request #22
Opened 2019-09-10 10:56 UTC by aashutoshbane

2019-09-10 11:27 UTC, supachris28 requested changes

2019-09-10 11:27 UTC, supachris28 commented on src/index.ts
> +  constructor(config: IClient, client: string = 'superagent') {
swapping these variables is a breaking change and unnecessary

2019-09-10 11:27 UTC, supachris28 commented on src/interfaces/webhook-config-interface.ts
> +export default interface IWebhookConfig {
this looks more default than just webhook-related, can be called something like IConfigItem

2019-09-10 11:27 UTC, supachris28 commented on src/interfaces/rustici-webhook-config-list.ts
> +import IWebhookConfig from './webhook-config-interface';
This can be more generic than jsut webhook based, can be something like IConfig

2019-09-10 12:09 UTC, supachris28 approved these changes

2019-09-10 12:09 UTC, supachris28 requested changes
Needs a version bump

2019-09-10 12:25 UTC, supachris28 approved these changes

2019-09-16 09:33 UTC, ukmadlz approved these changes

2019-09-16 09:55 UTC, merged